logging:
  level:
    root: WARN
    org.springframework: INFO
    org.apache.kafka: INFO
spring:
  kafka:
    security:
      protocol: "SSL"
    bootstrap-servers: kafka-1173818850-1-1295651234.scus.kafka-buabookkeeping-sox-stg.ms-df-messaging.prod-az-southcentralus-27.prod.us.walmart.net:9093,kafka-1173818850-2-1295651237.scus.kafka-buabookkeeping-sox-stg.ms-df-messaging.prod-az-southcentralus-27.prod.us.walmart.net:9093,kafka-1173818850-3-1295651240.scus.kafka-buabookkeeping-sox-stg.ms-df-messaging.prod-az-southcentralus-27.prod.us.walmart.net:9093,kafka-1173818850-4-1295651243.scus.kafka-buabookkeeping-sox-stg.ms-df-messaging.prod-az-southcentralus-27.prod.us.walmart.net:9093,kafka-1173818850-5-1295651246.scus.kafka-buabookkeeping-sox-stg.ms-df-messaging.prod-az-southcentralus-27.prod.us.walmart.net:9093,kafka-1173818850-6-1295651249.scus.kafka-buabookkeeping-sox-stg.ms-df-messaging.prod-az-southcentralus-27.prod.us.walmart.net:9093
    ssl:
      trust-store-location: 'file:/Users/k0d03gd/Library/CloudStorage/OneDrive-WalmartInc/BUA/share/buakafka.nonprod.wal-mart.com.jks'
      trust-store-password: BuaBookkeeping2021
      key-store-location:  'file:/Users/k0d03gd/Library/CloudStorage/OneDrive-WalmartInc/BUA/share/buakafka.nonprod.wal-mart.com.jks'
      key-store-password: BuaBookkeeping2021
    consumer:
      group-id: buatest
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      