logging:
  level:
    root: WARN
    org.springframework: INFO
    org.apache.kafka: INFO
spring:
  kafka:
    security:
      protocol: "SSL"
    bootstrap-servers: xxxxxxxxxxxxxxx
    ssl:
      trust-store-location: 'file:/Users/k0d03gd/Library/CloudStorage/OneDrive-WalmartInc/BUA/share/buakafka.nonprod.wal-mart.com.jks'
      trust-store-password: xxxxxxxxxxxxxxxxxxxx
      key-store-location:  'file:/Users/k0d03gd/Library/CloudStorage/OneDrive-WalmartInc/BUA/share/buakafka.nonprod.wal-mart.com.jks'
      key-store-password: xxxxxxxxxxxxxxxxx
    consumer:
      group-id: buatest
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
